[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_escrow = "9QtNXFDTA12LYCfu6XgYvqrdwb4wiUS2Fa5s7Asc4JxM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/nikhilkr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
