[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_vault = "68HpPyLbmx7QNRN9ygMVWzKVb6MVUbqCPkFJJj56BHQ2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/nikhilkr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
